import settable
import pygame

PYGAME_WINDOW_WIDTH = 1280
PYGAME_WINDOW_DEPTH = 768

RIGHT_MODE = "RIGHT"
LEFT_MODE = "LEFT"

WINDOW_BOTTOM = PYGAME_WINDOW_DEPTH
WINDOW_TOP = 0

GAME_WINDOW_RIGHT_EDGE = {
    RIGHT_MODE: 2 * PYGAME_WINDOW_WIDTH / 3,
    LEFT_MODE: PYGAME_WINDOW_WIDTH
}
GAME_WINDOW_LEFT_EDGE = {
    RIGHT_MODE: 0,
    LEFT_MODE: PYGAME_WINDOW_WIDTH / 3
}
DISPLAY_WINDOW_RIGHT_EDGE = {
    RIGHT_MODE: PYGAME_WINDOW_WIDTH,
    LEFT_MODE: PYGAME_WINDOW_WIDTH / 3
}
DISPLAY_WINDOW_LEFT_EDGE = {
    RIGHT_MODE: 2 * PYGAME_WINDOW_WIDTH / 3,
    LEFT_MODE: 0
}
HAND_WINDOW_POSITION = {
    RIGHT_MODE: (GAME_WINDOW_RIGHT_EDGE[RIGHT_MODE], 0),
    LEFT_MODE: (0, 0)
}
HAND_WINDOW_WIDTH = PYGAME_WINDOW_WIDTH / 3

HAND_GRAPHICAL_CENTER = (
    HAND_WINDOW_WIDTH / 2,
    PYGAME_WINDOW_DEPTH / 2
)

HAND_CENTERING_ADJUST = (- 125, 50)

HAND_REGION_SCALE_FACTOR = (3, 2)

HAND_REGION_DIMENSIONS = (
    HAND_REGION_SCALE_FACTOR[0] * HAND_WINDOW_WIDTH,
    HAND_REGION_SCALE_FACTOR[1] * PYGAME_WINDOW_DEPTH
)

HAND_REGION_CENTER = (
    HAND_REGION_DIMENSIONS[0] / 2,
    HAND_REGION_DIMENSIONS[1] / 2
)

HAND_REGION_POSITION = (
    HAND_GRAPHICAL_CENTER[0] - HAND_REGION_CENTER[0],
    HAND_GRAPHICAL_CENTER[1] - HAND_REGION_CENTER[1]
)

LEAP_VISION_MIN_COORDS = (-400, 0, -400)
LEAP_VISION_MAX_COORDS = (400, 400, 400)

GUI_WINDOW_RIGHT_EDGE = 3 * PYGAME_WINDOW_WIDTH / 4
GUI_WINDOW_LEFT_EDGE = PYGAME_WINDOW_WIDTH / 4
GUI_WINDOW_TOP_EDGE = PYGAME_WINDOW_DEPTH / 6
GUI_WINDOW_BOTTOM_EDGE = 5 * PYGAME_WINDOW_DEPTH / 6

GUI_WINDOW_DIMENSIONS = (
    GUI_WINDOW_RIGHT_EDGE - GUI_WINDOW_LEFT_EDGE,
    GUI_WINDOW_BOTTOM_EDGE - GUI_WINDOW_TOP_EDGE
)

GUI_WINDOW_POSITION = (
    GUI_WINDOW_LEFT_EDGE,
    GUI_WINDOW_TOP_EDGE
)

BUTTON_DIMENSIONS = (
    GUI_WINDOW_DIMENSIONS[0] / 3,
    GUI_WINDOW_DIMENSIONS[1] / 12
)

TEXT_BOX_DIMENSIONS = (
    GUI_WINDOW_DIMENSIONS[0] / 2,
    GUI_WINDOW_DIMENSIONS[1] / 12
)

BUTTON_LABEL_SIZE = 20
TEXT_BOX_TEXT_SIZE = 20
MENU_LABEL_SIZE = 40

GUI_WINDOW_COLOR = (0, 0, 0)
HAND_WINDOW_COLOR = (255, 255, 255)
GUI_BUTTON_COLOR = (255, 255, 255)
GUI_BUTTON_TEXT_COLOR = (0, 0, 0)
GUI_BUTTON_HIGHLIGHT = (200, 200, 200)
GUI_LABEL_TEXT_COLOR = (255, 255, 255)
TEXT_BOX_TEXT_COLOR = (0, 0, 0)
TEXT_BOX_COLOR = (180, 180, 180)
TEXT_BOX_HIGHLIGHT = (220, 220, 220)
TEXT_BOX_ACTIVE = (255, 255, 255)


# Game Logic

CIRCLE_DEG = 360.

GAME_MENU = "MENU"
GAME_PLAY = "PLAY"

MENU_NONE = "NONE"
MENU_MAIN = "MAIN"
MENU_NEW_CHAR = "NEW"
MENU_LOGIN = "LOGIN"
MENU_SETTINGS = "SETTINGS"
MENU_OVER = "OVER"

PLAYER_MAX_VEL = 25
ASTEROID_MAX_VEL = 20
ASTEROID_MIN_VEL = 5
STAR_MAX_VEL = 0
BULLET_VEL = 40

PLAYER_MAX_ANG_VEL = 10
ASTEROID_MAX_ANG_VEL = 5
STAR_MAX_ANG_VEL = 0
BULLET_MAX_ANG_VEL = 0

PLAYER_THICKNESS = 3
PLAYER_MAX_RADIUS = 20
PLAYER_COLLIDE_RADIUS = 15
PLAYER_ACCELERATION = 2
PLAYER_ANGULAR_ACCELERATION = 3

BULLET_RADIUS = 3
BULLET_RANGE = 10

ASTEROID_MAX_VERTICES = 15
ASTEROID_MIN_VERTICES = 7
ASTEROID_MAX_RADIUS = 40
ASTEROID_MIN_RADIUS = 25
ASTEROID_THICKNESS = 2
STAR_MIN_RADIUS = 3
STAR_MAX_RADIUS = 5

STAR_COUNT = 40

GAME_ARENA_DIMENSIONS = [
    GAME_WINDOW_RIGHT_EDGE[settable.HAND_MODE] - GAME_WINDOW_LEFT_EDGE[settable.HAND_MODE] + 2 * ASTEROID_MAX_RADIUS,
    WINDOW_BOTTOM + 2 * ASTEROID_MAX_RADIUS
]

PLAYER_START_POSITION = (GAME_ARENA_DIMENSIONS[0] / 2, GAME_ARENA_DIMENSIONS[1] / 2)

CORRECT_COUNT = 10

# File Path Parts
PARENT_DIR = "GameFinal/"
IMAGES_DIR = "images/"
DATA_DIR = "userData/"

PATH_TO_PROJECT = "/Users/Stover/Documents/LeapSDK/lib/CS228/"
IMAGES_PATH = "{}{}".format(PARENT_DIR, IMAGES_DIR)
DATA_PATH = "{}{}".format(PARENT_DIR, DATA_DIR)

NN_CLASSIFIER_FILE = "classifier.p"
USER_DATABASE_FILE = "database.p"

TRAIN_0_FILE = "Clark_train0.p"
TEST_0_FILE = "Clark_test0.p"
TRAIN_0_FILE_LEFT = "Clark_train0_left.p"
TEST_0_FILE_LEFT = "Clark_test0_left.p"

TRAIN_1_FILE = "Newton_train1.p"
TEST_1_FILE = "Newton_test1.p"
TRAIN_1_FILE_LEFT = "Giroux_train1_left.p"
TEST_1_FILE_LEFT = "Giroux_test1_left.p"

TRAIN_2_FILE = "Apple_train2.p"
TEST_2_FILE = "Apple_test2.p"
TRAIN_2_FILE_LEFT = "Giroux_train2_left.p"
TEST_2_FILE_LEFT = "Giroux_test2_left.p"

TRAIN_3_FILE = "Apple_train3.p"
TEST_3_FILE = "Apple_test3.p"
TRAIN_3_FILE_LEFT = "Gordon_train3_left.p"
TEST_3_FILE_LEFT = "Gordon_test3_left.p"

TRAIN_4_FILE = "Deluca_train4.p"
TEST_4_FILE = "Deluca_test4.p"
TRAIN_4_FILE_LEFT = "Ogilvie_train4_left.p"
TEST_4_FILE_LEFT = "Ogilvie_test4_left.p"

TRAIN_5_FILE = "Deluca_train5.p"
TEST_5_FILE = "Deluca_test5.p"
TRAIN_5_FILE_LEFT = "Warren_train5_left.p"
TEST_5_FILE_LEFT = "Warren_test5_left.p"

TRAIN_6_FILE = "Boland_train6.p"
TEST_6_FILE = "Boland_test6.p"
TRAIN_6_FILE_LEFT = "Wu_train6_left.p"
TEST_6_FILE_LEFT = "Wu_test6_left.p"

TRAIN_7_FILE = "Erickson_train7.p"
TEST_7_FILE = "Erickson_test7.p"
TRAIN_7_FILE_LEFT = "Landay_train7_left.p"
TEST_7_FILE_LEFT = "Landay_test7_left.p"

TRAIN_8_FILE = "Erickson_train8.p"
TEST_8_FILE = "Erickson_test8.p"
TRAIN_8_FILE_LEFT = "Burleson_train8_left.p"
TEST_8_FILE_LEFT = "Burleson_test8_left.p"

TRAIN_9_FILE = "Lee_train9.p"
TEST_9_FILE = "Lee_test9.p"
TRAIN_9_FILE_LEFT = "Childs_train9_left.p"
TEST_9_FILE_LEFT = "Childs_test9_left.p"
